"""Generate the per-panel perturbation profile CSV used by send_to_basyx.py.

Separate from the sender on purpose: the generated profiles are meant to be
inspected (open the CSV, sanity-check the values) before ever being used to
simulate/send anything.
"""

from pathlib import Path
from typing import Optional

import typer

from asset_forge import config
from asset_forge.integration.sensor_targets import load_targets
from configs import DATA_DIR
from perturbation import apply_anomaly, generate_profiles

app = typer.Typer(add_completion=False)


def _panel_tags(aasserver_path: Path) -> list[str]:
    """Return every distinct panel asset tag found in a DataBridge config.

    Args:
        aasserver_path: Path to an ``aasserver.json`` as generated by
            ``asset-forge convert --databridge``.

    Returns:
        Sorted, deduplicated list of panel asset tags (e.g.
        ``["PANEL-1529520", "PANEL-1529522", ...]``). Entries for other
        asset types (e.g. ``"INVERTER"``) are excluded.
    """
    targets = load_targets(aasserver_path)
    tags = {target.asset_tag for target in targets if target.asset_tag.startswith("PANEL-")}
    return sorted(tags)


@app.command()
def main(
    mode: str = typer.Option("uniform", "--mode", help="'uniform' or 'perturbed'"),
    seed: Optional[int] = typer.Option(None, "--seed", help="RNG seed for --mode perturbed"),
    irradiance_noise_std: float = typer.Option(0.05, "--irradiance-noise-std"),
    temperature_noise_std: float = typer.Option(1.0, "--temperature-noise-std"),
    aasserver_path: Path = typer.Option(
        config.DATABRIDGE_DIR / "aasserver.json", "--aasserver-path", exists=True
    ),
    output: Path = typer.Option(DATA_DIR / "panel_profiles.csv", "--output"),
) -> None:
    """Write one perturbation profile per panel found in aasserver.json.

    Args:
        mode: ``"uniform"`` for a neutral profile (every panel identical) or
            ``"perturbed"`` for seeded per-panel random variation -- see
            :func:`perturbation.generate_profiles`.
        seed: RNG seed, only used when ``mode="perturbed"``. Passing the
            same seed reproduces the exact same profiles.
        irradiance_noise_std: Passed through to
            :func:`perturbation.generate_profiles`.
        temperature_noise_std: Passed through to
            :func:`perturbation.generate_profiles`.
        aasserver_path: DataBridge config to read panel tags from (see
            :func:`_panel_tags`).
        output: Where to write the resulting profile CSV. Created (including
            parent directories) or overwritten.
    """
    panel_tags = _panel_tags(aasserver_path)
    if not panel_tags:
        typer.echo(f"no PANEL- targets found in {aasserver_path}", err=True)
        raise typer.Exit(code=1)

    profiles = generate_profiles(
        panel_tags,
        mode=mode,
        seed=seed,
        irradiance_noise_std=irradiance_noise_std,
        temperature_noise_std=temperature_noise_std,
    )

    # Example of forcing a deliberate deviation into specific panels, to
    # exercise alarm/anomaly-detection logic downstream. Uncomment and edit
    # the panel tag(s) as needed:
    #
    # profiles = apply_anomaly(
    #     profiles, [panel_tags[0]], irradiance_factor=0.2, temperature_offset=15.0
    # )

    output.parent.mkdir(parents=True, exist_ok=True)
    profiles.to_csv(output, index=False)
    typer.echo(f"wrote {len(profiles)} panel profile(s) to {output}")


if __name__ == "__main__":
    app()
