"""Super-dummy mock sensor: writes synthetic values straight into BaSyx's
own submodel-element `$value` endpoints, then reads each one back from the
server -- a throwaway local test harness proving the write path and read
path agree on the exact same live data. Not the real external OPC UA sensor
service (see export/aas/databridge.py's module docstring) -- that's a
separate service someone else builds; this bypasses OPC UA entirely and
talks to BaSyx directly over its own REST API, purely for local
verification that everything landed in the right, unified place.

Also historizes every value into InfluxDB, matching the `timeseries`
submodel's `LinkedSegment.Query` (see export/aas/submodels.py). BaSyx itself
only ever holds each Property's *current* value regardless of backend --
there is no history there to lose -- so this is the only place readings get
retained across time. One InfluxDB point per asset per round (all of a
panel's/inverter's variables as separate fields on the same point, tagged
by its asset_tag), not one point per variable, so the timeseries
submodel's single Query returns every one of that asset's variables
together.

Driven by `infra/databridge/aasserver.json`, already generated by
`asset-forge convert --databridge` -- so it exercises exactly the same
(submodel, idShortPath) pairs the real DataBridge bridge would write to,
with no need to re-derive the panel/inverter list here. The InfluxDB
`asset` tag (e.g. "PANEL-1529520") is recovered from each entry's `uniqueId`
by stripping its known variable suffix (see `_derive_asset_tag`) rather than
adding a new field to databridge.py's JSON output, so that file's shape
stays exactly what the real BaSyx DataBridge component expects.

Confirmed live against a real BaSyx aas-environment (2.0.0-SNAPSHOT): the
`$value` PATCH body must be the value JSON-encoded *as a string* (e.g.
`"42.5"`, not a bare `42.5`) -- a bare JSON number 500s. This matches AAS's
ValueOnly serialization, which represents xs:double/xs:float this way to
avoid cross-language precision loss; GET on the same endpoint returns the
same quoted-string form.
"""

import json
import random
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, NamedTuple

import requests
import typer
from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS
from loguru import logger

from asset_forge import config
from asset_forge.export.aas.solar import INVERTER_VARIABLES, PANEL_VARIABLES
from asset_forge.ingestion.loader import PathLike

app = typer.Typer(add_completion=False)

# Longest-suffix-first so e.g. a hypothetical "DC" wouldn't shadow "VDC".
_ALL_TAG_SUFFIXES = tuple(
    sorted({v.tag_suffix for v in (*PANEL_VARIABLES, *INVERTER_VARIABLES)}, key=len, reverse=True)
)


class SensorTarget(NamedTuple):
    submodel_id_b64: str
    id_short: str
    asset_tag: str


def _derive_asset_tag(node_id: str) -> str:
    for suffix in _ALL_TAG_SUFFIXES:
        marker = f"-{suffix}"
        if node_id.endswith(marker):
            return node_id[: -len(marker)]
    return node_id


def load_targets(aasserver_path: PathLike) -> List[SensorTarget]:
    """Parse `aasserver.json`'s sink entries into (submodel id, idShort,
    asset tag) targets. Only the base64url submodel id and idShortPath are
    kept from `submodelEndpoint` -- that also bakes in a host/port, but
    that's the in-Docker-network hostname (e.g. "aas-environment"), not
    necessarily reachable from wherever this runs."""
    entries = json.loads(Path(aasserver_path).read_text())
    targets = []
    for entry in entries:
        submodel_id_b64 = entry["submodelEndpoint"].rsplit("/submodels/", 1)[1]
        node_id = entry["uniqueId"][len("aas-") :] if entry["uniqueId"].startswith("aas-") else entry["uniqueId"]
        targets.append(SensorTarget(submodel_id_b64, entry["idShortPath"], _derive_asset_tag(node_id)))
    return targets


def _value_url(host: str, port: int, target: SensorTarget) -> str:
    return f"http://{host}:{port}/submodels/{target.submodel_id_b64}/submodel-elements/{target.id_short}/$value"


def write_value(host: str, port: int, target: SensorTarget, value: float) -> None:
    resp = requests.patch(_value_url(host, port, target), json=str(value), timeout=10)
    resp.raise_for_status()


def read_value(host: str, port: int, target: SensorTarget) -> float:
    resp = requests.get(_value_url(host, port, target), timeout=10)
    resp.raise_for_status()
    return float(resp.json())


@app.command()
def run(
    aasserver_path: Path = typer.Option(
        config.DATABRIDGE_DIR / "aasserver.json", "--aasserver-path", exists=True
    ),
    host_aas_env: str = typer.Option(config.AAS_ENV_HOST, "--host-aas-env"),
    port_aas_env: int = typer.Option(config.AAS_ENV_PORT, "--port-aas-env"),
    influx_host: str = typer.Option(config.INFLUXDB_HOST, "--influx-host"),
    influx_port: int = typer.Option(config.INFLUXDB_PORT, "--influx-port"),
    influx_org: str = typer.Option(config.INFLUXDB_ORG, "--influx-org"),
    influx_bucket: str = typer.Option(config.INFLUXDB_BUCKET, "--influx-bucket"),
    influx_token: str = typer.Option(config.INFLUXDB_TOKEN, "--influx-token"),
    interval: float = typer.Option(2.0, "--interval", help="seconds between write/read rounds"),
    once: bool = typer.Option(False, "--once", help="do one write+read round per target, then exit"),
) -> None:
    """Every `interval` seconds (or once, with --once): write a fresh
    random value into every (submodel, Property) pair listed in
    `aasserver_path`, read each one straight back from BaSyx to confirm it
    matches, and historize the whole round into InfluxDB (one point per
    asset, one field per variable)."""
    targets = load_targets(aasserver_path)
    if not targets:
        typer.echo(f"no targets found in {aasserver_path} -- run `asset-forge convert --databridge` first", err=True)
        raise typer.Exit(code=1)
    logger.info(
        f"driving {len(targets)} sensor Properties against {host_aas_env}:{port_aas_env}, "
        f"historizing to {influx_host}:{influx_port}/{influx_bucket}"
    )

    influx_client = InfluxDBClient(url=f"http://{influx_host}:{influx_port}", token=influx_token, org=influx_org)
    influx_write_api = influx_client.write_api(write_options=SYNCHRONOUS)

    while True:
        ok = mismatched = failed = 0
        now = datetime.now(timezone.utc)
        points_by_asset: Dict[str, Point] = {}

        for target in targets:
            value = round(random.uniform(0, 100), 2)
            try:
                write_value(host_aas_env, port_aas_env, target, value)
                readback = read_value(host_aas_env, port_aas_env, target)
            except requests.RequestException as exc:
                failed += 1
                logger.warning(f"{target.submodel_id_b64[:16]}.../{target.id_short}: request failed: {exc}")
                continue

            if readback == value:
                ok += 1
            else:
                mismatched += 1
                logger.warning(
                    f"{target.submodel_id_b64[:16]}.../{target.id_short}: wrote {value}, read back {readback}"
                )

            point = points_by_asset.setdefault(
                target.asset_tag, Point("sensor_reading").tag("asset", target.asset_tag).time(now)
            )
            point.field(target.id_short, readback)

        if points_by_asset:
            influx_write_api.write(bucket=influx_bucket, record=list(points_by_asset.values()))

        logger.info(
            f"round complete: {ok} ok, {mismatched} mismatched, {failed} failed (of {len(targets)}); "
            f"historized {len(points_by_asset)} asset(s) to InfluxDB"
        )
        if once:
            break
        time.sleep(interval)


if __name__ == "__main__":
    app()
